In [1]:
import numpy as np

In [2]:
arr = np.array([2,4,5,6])
arr**2

array([ 4, 16, 25, 36])

In [3]:
print(2*arr**2)

[ 8 32 50 72]


In [6]:
arr = np.array([2,4,5,6])
print(arr+2)
print(arr-2)

[4 6 7 8]
[0 2 3 4]


In [10]:
arr1d= np.array([[1,4,5,6,],[5,2,6,8]])
arr2d=np.array([5,7,3,8])
result = arr1d + arr2d
print(result)

[[ 6 11  8 14]
 [10  9  9 16]]


In [13]:
arrm = np.array([[1,3,5,6],
                [2,5,7,8],
                [6,8,2,7],
                [6,7,8,2]])
mn = arrm.mean()
std = arrm.std()
result = (arrm-mn)/std
print(result)
                

[[-1.78113395 -0.93044311 -0.07975227  0.34559316]
 [-1.35578853 -0.07975227  0.77093858  1.196284  ]
 [ 0.34559316  1.196284   -1.35578853  0.77093858]
 [ 0.34559316  0.77093858  1.196284   -1.35578853]]


In [14]:
arr = np.array([2,4,5,6])

In [19]:
np.exp(arr)

array([  7.3890561 ,  54.59815003, 148.4131591 , 403.42879349])

In [20]:
np.var(arr)

np.float64(2.1875)

In [21]:
np.log(arr)

array([0.69314718, 1.38629436, 1.60943791, 1.79175947])

In [24]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
arr.mean()

np.float64(4.25)

In [27]:
np.mean(arr)

np.float64(4.25)

In [29]:
arr.exp()

AttributeError: 'numpy.ndarray' object has no attribute 'exp'