In [1]:
import numpy as np

In [3]:
arr = np.array([1 ,5, 7, 9])

In [4]:
arr

array([1, 5, 7, 9])

In [6]:
arr2d = np.array([[10 , 29 ,59] , [2 , 5, 9]])

In [7]:
arr2d

array([[10, 29, 59],
       [ 2,  5,  9]])

In [10]:
np.zeros((3 , 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr.shape

(2, 3)

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr.size

6

In [20]:
arr.ndim

2

In [21]:
arr.astype(np.int32)

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)

In [22]:
arr.ndim

2

In [24]:
arr.dtype

dtype('int64')

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

In [26]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])