In [1]:
import numpy as np

In [5]:
arr = np.array([1,4,6,7])
print(arr[3])
print(arr[0])

7
1


In [6]:
arr[0:2]

array([1, 4])

In [9]:
print(arr[0:2])

[1 4]


In [10]:
print(arr[1:4])

[4 6 7]


In [11]:
arr1 = np.array([10, 20, 30, 40, 50])

In [12]:
arr1[1:4]

array([20, 30, 40])

In [13]:
arr[1] = 20

In [14]:
arr1

array([10, 20, 30, 40, 50])

In [19]:
sliced = arr1[1:4]
sliced[0] = 20

In [17]:
print(sliced)

[20 30 40]


In [21]:
sliced[1] = 10
print(sliced)

[20 10 40]


In [22]:
print(arr1)

[10 20 10 40 50]


In [24]:
arr1 = np.array([10, 20, 30, 40, 50])

In [31]:
arr1[[0,2,3]]

array([10, 30, 40])

In [29]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] # Indices to select
print(arr[idx]) # [10 30 50]



[10 30 50]


In [34]:
arr = np.array([10, 20, 30, 40, 50])
arr[arr>3]

array([10, 20, 30, 40, 50])