In [1]:
import numpy as np

In [8]:
arr = np.array([[10 ,20 ,30],
                [34 ,53 ,55],
                [23 ,52 ,25]])

In [10]:
arr.ndim

2

In [16]:
np.sum(arr, axis=0)

array([ 67, 125, 110])

In [17]:
print(np.sum(arr, axis=1))

[ 60 142 100]


In [19]:
arr[1,2]

np.int64(55)

In [20]:
print(arr[1,2])

55


In [21]:
print(arr[0:2, 1:2])

[[20]
 [53]]


In [22]:
arr3d = np.array([[[1 ,3 ,5],[4 ,22,25]],[[52,26,21],[27,262,62]]])

In [36]:
arr3d
arr3d[1,2,5]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [32]:
arr3d[0:2:2]=26

In [33]:
arr3d

array([[[26, 26, 26],
        [26, 26, 26]],

       [[24, 24, 24],
        [24, 24, 24]]])

In [34]:
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [35]:
arr[1,2]

np.int64(6)